/**
 * CalcLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';


const APIException = require('./APIException');

/**
 * Creates an instance of CouldNotComputeException
 */
class CouldNotComputeException extends APIException {
    /**
     * @constructor
     */
    constructor() {
        super();
        /**
         * Represents the server's exception message
         */
        this.serverMessage = null;

        /**
         * Represents the server's error code
         */
        this.serverCode = null;
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'serverMessage', realName: 'ServerMessage' },
            { name: 'serverCode', realName: 'ServerCode' },
        ]);
    }
}

module.exports = CouldNotComputeException;
