/**
 * CalcLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';


const Configuration = {
    // The base Uri for API calls
    BASEURI: 'http://examples.apimatic.io/apps/calculator',

};

module.exports = Configuration;
